name: 💚 规则提交
description: 提交自动记账规则

body:
  - type: markdown
    attributes:
      value: |
        > 注意:上面的标题部分请按照命名要求填写。
        > 命名规则：
        > 1.名称需要简洁，容易让人辩识。
        > 2.自动分类直接填写名称
        > 3.app数据、通知类需要加前缀，前缀名为App名称。例如：【微信】发红包、【微信】公众号_招行信用卡_支出
        > 4.短信需要加前缀，前缀名为短信发送方名称。例如：【中国银行】储蓄卡_支出
        > 5.标题不符合要求的将被直接关闭。
  - type: textarea
    id: logs
    attributes:
      label: Update Log/更新日志
      placeholder: |
        ...
  - type: 规则数据
    id: regulars
    attributes:
      label: Data/数据
      placeholder: |
      ...


