name: 🎉 自动记账规则提交
description: 提交自动记账规则


<!--template:reg-->
<!--label-->
<!--Please do not delete the above two notes. Just log in to your account and submit [issue]-->
<!--上面2个注释请勿删除，登录您的帐号提交【issue】即可-->
<!--填写数据请往下滑动-->

**Update Log/更新日志**



**Data/数据**

```json
        <!--请删除本行并粘贴数据-->
```






      


