name: 🎉 微信适配
description: 提交微信适配规则
labels: ["wechat"]

body:
  - type: markdown
    attributes:
      value: |
        > 注意:上面的标题部分请按照命名要求填写。
        > 命名规则：
        > 【微信适配】加版本号，比如 【微信适配】8.0.19
        
 
  - type: textarea
    id: regulars
    attributes:
      label: Data/数据
      value : |
        ```json
        <!--请删除本行并粘贴数据-->
        ```


